Repository sparkdotfi/spark-alm-controller, pull requests merged in 2024-12, with the labels that each got.

#65 feat: Add rate limited withdrawals (SC-858)
  src/ForeignController.sol
  src/MainnetController.sol
  test/base-fork/Aave.t.sol
  test/base-fork/Morpho.t.sol
  test/mainnet-fork/4626Calls.t.sol
  test/mainnet-fork/Aave.t.sol
Labels: Priority: High, Status: Ready for Review

#63 feat: Add JSONs to deployments (SC-859)
  Makefile
  script/Deploy.s.sol
  script/input/1/base-production.json
  script/input/1/base-staging.json
  script/input/1/base.json
  script/input/1/mainnet-production.json
  script/input/1/mainnet-staging.json
  script/input/1/mainnet.json
  script/output/1/base-production-release-20241023.json
  script/output/1/base-staging-release-20241022.json
  script/output/1/mainnet-production-release-20241023.json
  script/output/1/mainnet-staging-release-20241022.json
Labels: Priority: High, Status: Revisions Needed

#67 feat: Update constructor to remove susds (SC-871)
  deploy/ControllerDeploy.sol
  deploy/ControllerInit.sol
  script/Deploy.s.sol
  script/staging/StagingDeploymentBase.sol
  script/staging/test/DeployEthereum.t.sol
  src/MainnetController.sol
  test/mainnet-fork/DeployAndInit.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/unit/controllers/Admin.t.sol
  test/unit/controllers/Constructor.t.sol
  test/unit/controllers/Freeze.t.sol
  test/unit/deployments/Deploy.t.sol
  test/unit/mocks/MockSUsds.sol
Labels: Priority: High, Status: Ready for Review

#66 feat: Refactor staging to simplify and new deploy (SC-873)
  Makefile
  deploy/ControllerInit.sol
  script/input/1/base-staging.json
  script/input/1/common.json
  script/input/1/mainnet-staging.json
  script/output/1/base-staging-deps-release-20241022.json
  script/output/1/base-staging-deps-release-20241210.json
  script/output/1/base-staging-release-20241022.json
  script/output/1/base-staging-release-20241210.json
  script/output/1/mainnet-staging-deps-release-20241022.json
  script/output/1/mainnet-staging-deps-release-20241210.json
  script/output/1/mainnet-staging-release-20241022.json
  script/output/1/mainnet-staging-release-20241210.json
  script/staging/DeployEthereum.s.sol
  script/staging/FullStagingDeploy.s.sol
  script/staging/mocks/MockDaiUsds.sol
  script/staging/mocks/MockPSM.sol
  script/staging/mocks/MockRateProvider.sol
  script/staging/mocks/MockSUsds.sol
  test/base-fork/DeployAndInit.t.sol
  test/mainnet-fork/DeployAndInit.t.sol
Labels: Priority: High, Status: Ready for Review

#69 feat: Use return value from cooldown (SC-864)
  src/MainnetController.sol
  test/mainnet-fork/Ethena.t.sol
Labels: Priority: High, Status: Ready for Merge

#70 feat: Add trust assumptions, new functionality to README (SC-863)
  README.md
  src/MainnetController.sol
Labels: Priority: High, Status: Ready for Review

#68 feat: Add infinite withdraw test coverage for AAVE (SC-862)
  test/base-fork/Aave.t.sol
  test/mainnet-fork/Aave.t.sol
Labels: Priority: Medium, Status: Ready for Review

#71 add ethena minter 50bps limit
  README.md
Labels: Priority: Critical, Status: Ready for Review

#72 test: Refactor to use getBlock (SC-887)
  foundry.toml
  test/base-fork/Aave.t.sol
  test/base-fork/ForkTestBase.t.sol
  test/mainnet-fork/Aave.t.sol
  test/mainnet-fork/Ethena.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
Labels: Priority: High, Status: Ready for Review

#73 test: Remove staging config tests, add e2e testing (SC-890)
  foundry.toml
  script/staging/test/DeployEthereum.t.sol
Labels: Priority: High, Status: Ready for Review

#74 chore: Rename staging tests file (SC-892)
  script/staging/test/StagingDeployment.t.sol
Labels: Priority: High, Status: Ready for Review

#75 fix: Update logo
  README.md
Labels: Priority: Low, Status: Ready for Review

#77 fix: Remove manual remappings and update test file name (SC-897)
  foundry.toml
  script/staging/FullStagingDeploy.s.sol
  script/staging/test/StagingDeployment.t.sol
  src/MainnetController.sol
  test/base-fork/ForkTestBase.t.sol
  test/base-fork/InitAndUpgrade.t.sol
  test/mainnet-fork/CCTPCalls.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/mainnet-fork/InitAndUpgrade.t.sol
Labels: Priority: High, Status: Ready for Review

#79 Add release and bump solc version
  foundry.toml
  script/output/1/base-production-release-20241229.json
  script/output/1/mainnet-production-release-20241229.json
Labels: Priority: High, Status: Ready for Review

#80 feat: Add upgrade scripts for simulations (SC-891)
  README.md
  script/Upgrade.s.sol
  script/input/1/base-production.json
Labels: Priority: High, Status: Ready for Review
