Repository sparkdotfi/spark-alm-controller, pull requests merged in 2024-09, with the labels that each got.

#19 [SC-641] CCTP split transfers
  src/ForeignController.sol
  src/MainnetController.sol
  src/interfaces/CCTPInterfaces.sol
  test/mainnet-fork/CCTPCalls.t.sol
Labels: Priority: Critical, Status: Ready for Review

#18 [SC-644] Add rate limits
  src/ForeignController.sol
  src/MainnetController.sol
  src/RateLimits.sol
  src/interfaces/CCTPInterfaces.sol
  src/interfaces/IALMProxy.sol
  src/interfaces/IRateLimits.sol
  test/base-fork/ForkTestBase.t.sol
  test/mainnet-fork/CCTPCalls.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/unit/controllers/Admin.t.sol
  test/unit/controllers/Constructor.t.sol
  test/unit/controllers/Freeze.t.sol
  test/unit/ratelimits/RateLimits.t.sol
Labels: Priority: Critical, Status: Ready for Review

#20 [SC-650] Rate limit integration tests
  test/base-fork/ForkTestBase.t.sol
  test/base-fork/PsmCalls.t.sol
  test/mainnet-fork/CCTPCalls.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/mainnet-fork/PsmCalls.t.sol
  test/mainnet-fork/VaultCalls.t.sol
Labels: Priority: Critical, Status: Ready for Review

#21 Add natspec to IALMProxy
  src/interfaces/IALMProxy.sol
Labels: Priority: Critical, Status: Ready for Review

#22 chore: Improve readability, add full README
  README.md
  src/ForeignController.sol
  src/MainnetController.sol
  src/RateLimitHelpers.sol
  src/RateLimits.sol
  src/interfaces/CCTPInterfaces.sol
  src/interfaces/IALMProxy.sol
  src/interfaces/IRateLimits.sol
  test/base-fork/ForkTestBase.t.sol
  test/base-fork/PsmCalls.t.sol
  test/mainnet-fork/CCTPCalls.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/unit/rate-limits/RateLimits.t.sol
Labels: Priority: Critical, Status: Ready for Merge

#23 feat: Add event for CCTP (SC-652)
  src/ForeignController.sol
  src/MainnetController.sol
  test/mainnet-fork/CCTPCalls.t.sol
Labels: Priority: Critical, Status: Ready for Review

#26 feat: Spearbit fixes (SC-668)
  src/ALMProxy.sol
  src/ForeignController.sol
  src/MainnetController.sol
  src/RateLimitHelpers.sol
  src/RateLimits.sol
  src/interfaces/IALMProxy.sol
  src/interfaces/IRateLimits.sol
  test/base-fork/ForkTestBase.t.sol
  test/mainnet-fork/CCTPCalls.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/unit/controllers/Admin.t.sol
  test/unit/controllers/Constructor.t.sol
  test/unit/controllers/Freeze.t.sol
  test/unit/mocks/MockPSM.sol
  test/unit/proxy/DoCall.t.sol
Labels: Priority: High, Status: Ready for Review

#25 test: Add fuzz testing for rate limits (SC-656)
  test/unit/rate-limits/RateLimits.t.sol
Labels: Priority: High, Status: Ready for Review

#24 test: Reorg tests (SC-654)
  test/unit/rate-limits/RateLimits.t.sol
Labels: Priority: High, Status: Ready for Review

#29 feat: Add Spearbit audit
  audits/report-maker-review-0916-alm.pdf
Labels: Priority: High, Status: Ready for Review

#27 feat: Add PSM refill on swap (SC-683)
  src/MainnetController.sol
  test/mainnet-fork/CCTPCalls.t.sol
  test/mainnet-fork/ForkTestBase.t.sol
  test/mainnet-fork/PsmCalls.t.sol
Labels: Priority: High, Status: Ready for Merge
